version: '3.3'

services:
  yourls:
    image: yourls:${YOURLS_IMAGE_VERSION:-latest}
    restart: always
    networks:
      - 'srv'
      - 'yourls-internal'
    restart: always
    depends_on:
      - yourls-db
    environment:
      YOURLS_SITE: https://${YOURLS_HOST:-yourls.${SITE:-localhost}}
      YOURLS_DB_HOST: yourls-db
      YOURLS_DB_NAME: ${YOURLS_MARIADB_DATABASE:-yourls}
      YOURLS_DB_USER: ${YOURLS_MARIADB_USER:-yourls}
      YOURLS_DB_PASS: ${YOURLS_MARIADB_PASSWORD:-yourls}
      YOURLS_USER: ${YOURLS_USER:-admin}
      YOURLS_PASS: ${YOURLS_PASS:-nimda}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.yourls.rule=Host(`${YOURLS_HOST:-yourls.${SITE:-localhost}}`)'
      - 'traefik.http.services.yourls.loadbalancer.server.port=80'
      - 'homepage.group=Web'
      - 'homepage.name=Yourls'
      - 'homepage.icon=nginx.png'
      - 'homepage.href=https://${NGINX_HOST:-${SITE:-localhost}}'
      - 'homepage.description=Default webserver for the server.'

  yourls-db:
    image: mariadb:${MARIADB_IMAGE_VERSION:-latest}
    restart: always
    healthcheck:
      test: ['CMD', 'mysqlcheck', '--all-databases', '-ppass']
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - 'yourls-internal'
    volumes:
      - './yourls/db:/var/lib/mysql'
    labels:
      - 'traefik.enable=false'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${YOURLS_MARIADB_USER:-yourls}
      MYSQL_DATABASE: ${YOURLS_MARIADB_DATABASE:-yourls}
      MYSQL_PASSWORD: ${YOURLS_MARIADB_PASSWORD:-yourls}

networks:
  yourls-internal:
