version: '3.8'

services:
  pydio-db:
    image: linuxserver/mariadb:${MARIADB_IMAGE_VERSION:-latest}
    platform: '${PLATFORM_ARCH}'
    container_name: pydio-db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      - 'pydio-internal'
    restart: unless-stopped
    environment:
      PUID: ${PYDIO_UID:-0}
      PGID: ${PYDIO_GID:-0}
      TZ: '${TIMEZONE:-Europe/Madrid}'
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-bXJyYmV1}pydio
      MYSQL_DATABASE: ${PYDIO_DB_DATABASE:-pydio}
      MYSQL_USER: ${PYDIO_DB_USER:-pydio}
      MYSQL_PASSWORD: ${PYDIO_DB_PASSWORD:-oidyp}
    volumes:
      - './pydio/db:/config'

  pydio-cells:
    image: linuxserver/pydio-cells:${PYDIO_IMAGE_VERSION:-latest}
    platform: '${PLATFORM_ARCH}'
    container_name: pydio-cells
    networks:
      - 'server'
      - 'pydio-internal'
    restart: unless-stopped
    depends_on:
      pydio-db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:8080']
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5
    environment:
      PUID: ${PYDIO_UID:-0}
      PGID: ${PYDIO_GID:-0}
      TZ: '${TIMEZONE:-Europe/Madrid}'
      EXTERNALURL: ${PYDIO_HOST:-pydio.${SITE:-localhost}}
    volumes:
      - './pydio/config:/config'
    ports:
      - '${PYDIO_GRPC_PORT:-33060}:33060'
    labels:
      # Traefik
      traefik.enable: true
      traefik.http.routers.pydio.rule: Host(`${PYDIO_HOST:-pydio.${SITE:-localhost}}`)
      traefik.http.services.pydio.loadbalancer.server.port: 8080
      traefik.http.services.pydio.loadbalancer.serverstransport: ignorecert
      traefik.http.services.pydio.loadbalancer.server.scheme: https

      # Homepage
      homepage.group: Web
      homepage.name: Pydio Cells
      homepage.icon: pydio.png
      homepage.href: https://${PYDIO_HOST:-pydio.${SITE:-localhost}}
      homepage.description: File Sharing & Sync Platform.

networks:
  pydio-internal:
