networks:
  server:
    ipam:
      config:
        - subnet: 172.22.0.0/16
  server-metrics: {}
  server-searxng: {}
  immich-internal: {}
  vikunja-internal: {}
  authelia-internal: {}
  dawarich-internal: {}
  open-webui-internal: {}
