version: '3.8'

services:
  nginx_mrrb_eu:
    image: nginx:${NGINX_IMAGE_VERSION:-stable-alpine}
    volumes:
      - './nginx/conf:/etc/nginx/conf.d'
      - './refs/server-private/page_mrrb.eu/:/srv/www/default'
      - './nginx/logs:/var/log/nginx/'
    networks:
      - 'server'
    restart: unless-stopped
    container_name: nginx_mrrb_eu
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx_mrrb_eu.rule=Host(`mrrb.eu`)'
      - 'traefik.http.services.nginx_mrrb_eu.loadbalancer.server.port=80'
      - 'homepage.group=Web'
      - 'homepage.name=NginX [mrrb.eu]'
      - 'homepage.icon=nginx.png'
      - 'homepage.href=https://mrrb.eu'
      - 'homepage.description=Main mrrb page.'
