# See https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings

use_default_settings: true

search:
  formats:
    - html
    - json

server:
  # secret_key: "yek_terces_gnxraes"  # Configured in compose file
  limiter: true
  image_proxy: true

# redis:
#   url: redis://redis:6379/0
