version: '3.3'

services:
  shlink:
    image: shlinkio/shlink:${SHLINK_IMAGE_VERSION:-stable}
    restart: always
    container_name: shlink-backend
    networks:
      - 'srv'
      - 'shlink-internal'
    restart: always
    depends_on:
      - shlink-db
    environment:
      # General
      DEFAULT_DOMAIN: ${SHLINK_HOST:-shlink.${SITE:-localhost}}
      IS_HTTPS_ENABLED: false
      GEOLITE_LICENSE_KEY: ${SHLINK_GEOLITE_LICENSE_KEY:-''}
      AUTO_RESOLVE_TITLES: ${SHLINK_AUTO_RESOLVE_TITLES:-false}
      TIMEZONE: ${SHLINK_TIMEZONE:-'Europe/Madrid'}
      MULTI_SEGMENT_SLUGS_ENABLED: ${SHLINK_MULTI_SEGMENT_SLUGS_ENABLED:-false}
      SHORT_URL_TRAILING_SLASH: ${SHLINK_SHORT_URL_TRAILING_SLASH:-true}
      SHORT_URL_MODE: ${SHLINK_SHORT_URL_MODE:-strict}

      # Database
      DB_DRIVER: maria
      DB_NAME: ${SHLINK_MARIADB_DATABASE:-shlink}
      DB_USER: ${SHLINK_MARIADB_USER:-shlink}
      DB_PASSWORD: ${SHLINK_MARIADB_PASSWORD:-shlink}
      DB_HOST: shlink-db

      # Visits tracking
      DISABLE_TRACKING: ${SHLINK_DISABLE_TRACKING:-false}
      DISABLE_IP_TRACKING: ${SHLINK_DISABLE_IP_TRACKING:-false}
      SKIP_INITIAL_GEOLITE_DOWNLOAD: true
    labels:
      # Traefik
      - 'traefik.enable=true'
      - "traefik.http.routers.shlink-backend.rule=Host(`${SHLINK_HOST:-shlink.${SITE:-localhost}}`)"
      - 'traefik.http.services.shlink-backend.loadbalancer.server.port=8080'
      # Homepage
      - 'homepage.group=Web'
      - 'homepage.name=Shlink admin panel'
      - 'homepage.icon=shlink.png'
      - 'homepage.href=https://${SHLINK_GUI_HOST:-admin.shlink.${SITE:-localhost}}'
      - 'homepage.description=The definitive self-hosted URL shortener.'

  shlink-web-client:
    image: shlinkio/shlink-web-client:${SHLINK_IMAGE_VERSION:-stable}
    restart: always
    container_name: shlink-gui
    networks:
      - 'srv'
    restart: always
    labels:
      # Traefik
      - 'traefik.enable=true'
      - 'traefik.http.routers.shlink-gui.rule=Host(`${SHLINK_GUI_HOST:-admin.shlink.${SITE:-localhost}}`)'
      - 'traefik.http.services.shlink-gui.loadbalancer.server.port=80'
      - 'traefik.http.routers.shlink-gui.middlewares=shadow_auth@docker'
      # Homepage
      - 'homepage.group=Web'
      - 'homepage.name=Shlink admin panel'
      - 'homepage.icon=shlink.png'
      - 'homepage.href=https://${SHLINK_GUI_HOST:-admin.shlink.${SITE:-localhost}}'
      - 'homepage.description=The definitive self-hosted URL shortener.'
    volumes:
      - './shlink/servers.json:/usr/share/nginx/html/servers.json'

  shlink-db:
    image: mariadb:${MARIADB_IMAGE_VERSION:-latest}
    restart: always
    container_name: shlink-db
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - 'shlink-internal'
    volumes:
      - './shlink/db:/var/lib/mysql'
    labels:
      - 'traefik.enable=false'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${SHLINK_MARIADB_USER:-shlink}
      MYSQL_DATABASE: ${SHLINK_MARIADB_DATABASE:-shlink}
      MYSQL_PASSWORD: ${SHLINK_MARIADB_PASSWORD:-shlink}

networks:
  shlink-internal:
