services:
  searxng:
    image: searxng/searxng:${SEARXNG_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: searxng

    environment:
      SEARXNG_BASE_URL: https://${SEARXNG_HOST:-searxng.${SITE:-localhost}}

      # python3 -c "import secrets; print(secrets.token_hex(32))"
      SEARXNG_SECRET_KEY: ${SEARXNG_SECRET_KEY:-ad3c2fc45baf07600bd469c5ebffe3f34276fc3b76ebe2ca6df6bc999fd6eaa6}

    networks:
      - server

    volumes:
      - './services/searxng/config/:/etc/searxng:rw'
      - './services/searxng/data/:/var/cache/searxng:rw'

    labels:
      ## Traefik
      traefik.enable: true

      traefik.http.services.searxng.loadbalancer.server.port: 8080

      traefik.http.routers.searxng.entrypoints: web,websecure
      traefik.http.routers.searxng.service: searxng
      traefik.http.routers.searxng.rule: Host(`${SEARXNG_HOST:-searxng.${SITE:-localhost}}`)

      ## Homepage
      homepage.group: Web
      homepage.name: searxng
      homepage.icon: go.png
      homepage.href: https://${SEARXNG_HOST:-searxng.${SITE:-localhost}}
      homepage.description: Internet metasearch engine. Users are neither tracked nor profiled.

  # ToDo: Add valkey/redis??
