services:
  searxng:
    image: searxng/searxng:${SEARXNG_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: searxng

    environment:
      SEARXNG_BASE_URL: https://${SEARXNG_HOST:-searxng.${SITE:-localhost}}

    depends_on:
      - valkey

    networks:
      - server
      - server-searxng

    volumes:
      - './services/searxng/config/:/etc/searxng:rw'
      - './services/searxng/data/:/var/cache/searxng:rw'

    labels:
      ## Traefik
      traefik.enable: true

      traefik.http.services.searxng.loadbalancer.server.port: 8080

      traefik.http.routers.searxng.entrypoints: web,websecure
      traefik.http.routers.searxng.service: searxng
      traefik.http.routers.searxng.rule: Host(`${SEARXNG_HOST:-searxng.${SITE:-localhost}}`)

      ## Homepage
      homepage.group: Web
      homepage.name: searxng
      homepage.icon: go.png
      homepage.href: https://${SEARXNG_HOST:-searxng.${SITE:-localhost}}
      homepage.description: Internet metasearch engine. Users are neither tracked nor profiled.

  searxng-valkey:
    image: valkey/valkey:${SEARXNG_VALKEY_IMAGE_VERSION:-8-alpine}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: searxng-valkey

    networks:
      - server-searxng

    command: valkey-server --save "" --appendonly no

    volumes:
      - './services/searxng/valkey:/data'
