version: '3'

services:
  simply-shorten:
    image: draganczukp/simply-shorten:${SIMPLYSHORTEN_IMAGE_VERSION:-latest}
    container_name: simply-shorten
    networks:
      - 'server'
    restart: unless-stopped
    environment:
      - username=${SIMPLYSHORTEN_USER:-username}
      - password=${SIMPLYSHORTEN_PASS:-p1kKjazX54u27}
    volumes:
      - ./simply-shorten/urls.sqlite:/urls.sqlite
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.simply-shorten.rule=Host(`${SIMPLYSHORTEN_HOST:-simply-shorten.${SITE:-localhost}}`)'
      - 'traefik.http.services.simply-shorten.loadbalancer.server.port=4567'
      - 'homepage.group=Web'
      - 'homepage.name=Simply Shorten'
      - 'homepage.href=https://${SIMPLYSHORTEN_HOST:-simply-shorten.${SITE:-localhost}}'
      - 'homepage.description=A simple selfhosted URL shortener with no unnecessary features.'
