services:
  syncthing:
    image: syncthing/syncthing:${SYNCTHING_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    hostname: ${SYNCTHING_HOST:-syncthing.${SITE:-localhost}}
    container_name: syncthing

    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:8384']
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5

    environment:
      PUID: ${STORAGE_UID:-0}
      PGID: ${STORAGE_GID:-0}

    networks:
      - server

    volumes:
      - './services/syncthing/data/:/var/syncthing/'
      - './storage/mount/gocryptfs:/mnt_host/gocryptfs'

    labels:
      ## Traefik
      traefik.enable: true

      traefik.http.services.syncthing.loadbalancer.server.port: 8384

      traefik.http.routers.syncthing.entrypoints: web,websecure
      traefik.http.routers.syncthing.service: syncthing
      traefik.http.routers.syncthing.rule: Host(`${SYNCTHING_HOST:-syncthing.${SITE:-localhost}}`)

      traefik.tcp.services.syncthing.loadbalancer.server.port: ${TRAEFIK_SYNCTHING_ENTRYPOINT:-22000}

      traefik.tcp.routers.syncthing.entrypoints: syncthing
      traefik.tcp.routers.syncthing.service: syncthing
      traefik.tcp.routers.syncthing.rule: HostSNI(`*`)

      traefik.udp.services.syncthing.loadbalancer.server.port: ${TRAEFIK_SYNCTHING_ENTRYPOINT:-22000}

      traefik.udp.routers.syncthing.entrypoints: syncthing
      traefik.udp.routers.syncthing.service: syncthing
      traefik.udp.routers.syncthing.rule: HostSNI(`*`)

      ## Homepage
      homepage.group: Files
      homepage.name: Syncthing
      homepage.icon: syncthing.png
      homepage.href: https://${SYNCTHING_HOST:-syncthing.${SITE:-localhost}}
      homepage.description: Continuous file synchronization.


  syncthing-relaysrv:
    image: syncthing/relaysrv:${SYNCTHING_RELAYSRV_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    hostname: syncthing-relaysrv
    container_name: syncthing-relaysrv

    labels:
      ## Traefik
      traefik.enable: true

      traefik.tcp.services.syncthing-relaysrv.loadbalancer.server.port: ${TRAEFIK_SYNCTHING_RELAYSRV_ENTRYPOINT:-22067}

      traefik.tcp.routers.syncthing-relaysrv.entrypoints: syncthing-relaysrv
      traefik.tcp.routers.syncthing-relaysrv.service: syncthing-relaysrv
      traefik.tcp.routers.syncthing-relaysrv.rule: HostSNI(`*`)

      traefik.tcp.services.syncthing-relaysrv-status.loadbalancer.server.port: ${TRAEFIK_SYNCTHING_RELAYSRV_STATUS_ENTRYPOINT:-22070}

      traefik.tcp.routers.syncthing-relaysrv-status.entrypoints: syncthing-relaysrv-status
      traefik.tcp.routers.syncthing-relaysrv-status.service: syncthing-relaysrv-status
      traefik.tcp.routers.syncthing-relaysrv-status.rule: HostSNI(`*`)
