version: '3.8'

services:
  nextcloud-db:
    image: mariadb:${MARIADB_IMAGE_VERSION:-latest}
    platform: '${PLATFORM_ARCH}'
    restart: unless-stopped
    container_name: nextcloud-db
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - 'nextcloud-internal'
    volumes:
      - './nextcloud/db:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${NEXTCLOUD_MARIADB_USER:-nextcloud}
      MYSQL_DATABASE: ${NEXTCLOUD_MARIADB_DATABASE:-nextcloud}
      MYSQL_PASSWORD: ${NEXTCLOUD_MARIADB_PASSWORD:-duolctxen}
      TZ: '${TIMEZONE:-Europe/Madrid}'
    labels:
      traefik.enable: false

  nextcloud-app:
    image: nextcloud:${NEXTCLOUD_IMAGE_VERSION:-stable-apache}
    platform: '${PLATFORM_ARCH}'
    restart: unless-stopped
    container_name: nextcloud-app
    depends_on:
      nextcloud-db:
        condition: service_healthy
    networks:
      - 'nextcloud-internal'
    environment:
      MYSQL_USER: ${NEXTCLOUD_MARIADB_USER:-nextcloud}
      MYSQL_DATABASE: ${NEXTCLOUD_MARIADB_DATABASE:-nextcloud}
      MYSQL_PASSWORD: ${NEXTCLOUD_MARIADB_PASSWORD:-duolctxen}
      MYSQL_HOST: nextcloud-db
    volumes:
      - './nextcloud/data/:/var/www/html'
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`${NEXTCLOUD_HOST:-nextcloud.s${SITE:-localhost}}`)
      traefik.http.services.nextcloud.loadbalancer.server.port: 80

      # https://docs.nextcloud.com/server/22/admin_manual/installation/harden_server.html
      # https://doc.traefik.io/traefik/v2.6/middlewares/http/headers/
      traefik.http.middlewares.nextcloud-header.headers.stsincludesubdomains: true
      traefik.http.middlewares.nextcloud-header.headers.stspreload: true
      traefik.http.middlewares.nextcloud-header.headers.stsseconds: 15552000
      traefik.http.middlewares.nextcloud-header.headers.customFrameOptionsValue: SAMEORIGIN
      traefik.http.middlewares.nextcloud-header.headers.browserXssFilter: true
      traefik.http.middlewares.nextcloud-header.headers.contentTypeNosniff: true
      traefik.http.middlewares.nextcloud-header.headers.referrerPolicy: no-referrer

      # https://docs.nextcloud.com/server/21/admin_manual/issues/general_troubleshooting.html#service-discovery
      # https://docs.nextcloud.com/server/23/admin_manual/configuration_server/reverse_proxy_configuration.html#traefik-2
      # https://doc.traefik.io/traefik/v2.6/middlewares/http/redirectregex/
      traefik.http.middlewares.nextcloud-redirect-dav.redirectRegex.permanent: true
      traefik.http.middlewares.nextcloud-redirect-dav.redirectRegex.regex: https://${NEXTCLOUD_HOST:-nextcloud.s${SITE:-localhost}}/.well-known/(card|cal)'dav
      traefik.http.middlewares.nextcloud-redirect-dav.redirectRegex.replacement: https://${NEXTCLOUD_HOST:-nextcloud.s${SITE:-localhost}}/remote.php/dav/'

      traefik.http.routers.nextcloud.middlewares: nextcloud-header,nextcloud-redirect-dav'

      homepage.group: Web
      homepage.name: Nextcloud
      homepage.icon: nextcloud.png
      homepage.href: https://${NEXTCLOUD_HOST:-nextcloud.s${SITE:-localhost}}
      homepage.description: Online collaboration platform.

networks:
  nextcloud-internal:
    name: nextcloud-internal
