version: '3'

services:
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_IMAGE_VERSION:-latest}
    environment:
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-true}
      WATCHTOWER_ROLLING_RESTART: ${WATCHTOWER_ROLLING_RESTART:-true}
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE:-'0 0 2 * * *'} # run at 2am everyday
    restart: always
    labels:
      traefik.enable: false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - 'homepage.group=Docker'
      - 'homepage.name=Watchtower'
      - 'homepage.icon=watchtower.png'
      - 'homepage.description=A container-based solution for automating Docker container base image updates'
