services:
  dawarich-db:
    image: postgres:${POSTGRES_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    hostname: dawarich-db
    container_name: dawarich-db

    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '${DAWARICH_POSTGRES_DB:-dawarich}']
      start_period: 30s
      interval: 15s
      timeout: 30s
      retries: 10

    networks:
      - dawarich-internal

    environment:
      POSTGRES_PASSWORD: ${DAWARICH_POSTGRES_PASSWORD:-hcirawad}
      POSTGRES_USER: ${DAWARICH_POSTGRES_USER:-dawarich}
      POSTGRES_DB: ${DAWARICH_POSTGRES_DB:-dawarich}

    volumes:
      - './services/dawarich/db:/var/lib/postgresql/data'
      - './services/dawarich/shared_data:/var/shared'
      - '/etc/localtime:/etc/localtime:ro'

    labels:
      ## Traefik
      traefik.enable: false

    # user: 1000:1000

  dawarich-redis:
    image: redis:${REDIS_IMAGE_VERSION:-alpine}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    hostname: dawarich-redis
    container_name: dawarich-redis

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 30s
      interval: 60s
      timeout: 30s
      retries: 5

    networks:
      - dawarich-internal

    command: redis-server --save 60 1 --loglevel warning

    volumes:
      - './services/dawarich/shared_data:/var/shared/redis'
      - '/etc/localtime:/etc/localtime:ro'

    labels:
      ## Traefik
      traefik.enable: false

    # user: 1000:1000

  dawarich:
    image: freikin/dawarich:${DAWARICH_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: dawarich

    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    stdin_open: true
    tty: true

    healthcheck:
      test: ['CMD', 'wget', '127.0.0.1:3000', '-O', '/dev/null']
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5

    environment:
      ## App config
      # RAILS_ENV: 'development'
      TIME_ZONE: '${TIMEZONE:-Europe/Madrid}'
      DISTANCE_UNIT: km
      APPLICATION_HOST: '${DAWARICH_HOST:-dawarich.${SITE:-localhost}}'
      APPLICATION_HOSTS: '${DAWARICH_HOST:-dawarich.${SITE:-localhost}},localhost,127.0.0.1'
      APPLICATION_PROTOCOL: http
      MIN_MINUTES_SPENT_IN_CITY: 60

      ## Redis config
      REDIS_URL: redis://dawarich-redis:6379/0

      ## DB config
      DATABASE_HOST: 'dawarich-db'
      DATABASE_USERNAME: '${DAWARICH_POSTGRES_USER:-dawarich}'
      DATABASE_PASSWORD: '${DAWARICH_POSTGRES_PASSWORD:-hcirawad}'
      DATABASE_NAME: '${DAWARICH_POSTGRES_DB:-dawarich}'

    depends_on:
      - dawarich-redis
      - dawarich-db

    networks:
      - server
      - dawarich-internal

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

    volumes:
      - './services/dawarich/gem_cache:/usr/local/bundle/gems'
      - './services/dawarich/public:/var/app/public'

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: '2G'

    labels:
      ## Traefik
      traefik.enable: true
      traefik.http.routers.dawarich.rule: Host(`${DAWARICH_HOST:-dawarich.${SITE:-localhost}}`)
      traefik.http.services.dawarich.loadbalancer.server.port: 3000

      ## Homepage
      homepage.group: Web
      homepage.name: Dawarich
      homepage.icon: https://${DAWARICH_HOST:-dawarich.${SITE:-localhost}}/assets/img/touch-icon-ipad-retina.png
      homepage.href: https://${DAWARICH_HOST:-dawarich.${SITE:-localhost}}
      homepage.description: Self-hosted alternative to Google Location History (Google Maps Timeline).

  dawarich-sidekiq:
    image: freikin/dawarich:${DAWARICH_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: dawarich-sidekiq

    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    stdin_open: true
    tty: true

    environment:
      ## App config
      # RAILS_ENV: 'development'
      TIME_ZONE: '${TIMEZONE:-Europe/Madrid}'
      DISTANCE_UNIT: km
      APPLICATION_HOST: '${DAWARICH_HOST:-dawarich.${SITE:-localhost}}'
      APPLICATION_HOSTS: '${DAWARICH_HOST:-dawarich.${SITE:-localhost}},localhost,127.0.0.1'
      APPLICATION_PROTOCOL: http
      MIN_MINUTES_SPENT_IN_CITY: 60

      ## Redis config
      REDIS_URL: redis://dawarich-redis:6379/0

      ## DB config
      DATABASE_HOST: 'dawarich-db'
      DATABASE_USERNAME: '${DAWARICH_POSTGRES_USER:-dawarich}'
      DATABASE_PASSWORD: '${DAWARICH_POSTGRES_PASSWORD:-hcirawad}'
      DATABASE_NAME: '${DAWARICH_POSTGRES_DB:-dawarich}'

      ## Other
      BACKGROUND_PROCESSING_CONCURRENCY: 10

    depends_on:
      - dawarich-redis
      - dawarich-db
      - dawarich

    networks:
      - dawarich-internal

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

    volumes:
      - './services/dawarich/gem_cache:/usr/local/bundle/gems'
      - './services/dawarich/public:/var/app/public'

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: '2G'

    labels:
      ## Traefik
      traefik.enable: false

networks:
  dawarich-internal:
