version: '3.8'

services:
  nginx:
    image: nginx:${NGINX_IMAGE_VERSION:-stable-alpine}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: nginx

    # healthcheck:
    #   test: ['CMD', 'curl', '0.0.0.0:80']
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5

    networks:
      - server

    volumes:
      - './services/nginx/conf:/etc/nginx/conf.d'
      - './refs/server-private/page_default/:/srv/www/default'
      - './services/nginx/logs:/var/log/nginx/'

    labels:
      ## Traefik
      traefik.enable: true
      traefik.http.routers.nginx.rule: Host(`${NGINX_HOST:-${SITE:-localhost}}`)
      traefik.http.services.nginx.loadbalancer.server.port: 80

      ## Homepage
      homepage.group: Web
      homepage.name: NginX [default]
      homepage.icon: nginx.png
      homepage.href: https://${NGINX_HOST:-${SITE:-localhost}}
      homepage.description: Default webserver for the server.
