services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: portainer

    networks:
      - server

    command: |
      -H unix:///var/run/docker.sock
    
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './services/portainer/data:/data'

    labels:
      ## Traefik
      traefik.enable: true

      ## Frontend
      traefik.http.services.portainer.loadbalancer.server.port: 9000

      traefik.http.routers.portainer.entrypoints: web,websecure
      traefik.http.routers.portainer.service: portainer
      traefik.http.routers.portainer.rule: Host(`${PORTAINER_HOST:-portainer.${SITE:-localhost}}`)

      ## Edge
      traefik.http.services.portainer-edge.loadbalancer.server.port: 8000

      traefik.http.routers.portainer-edge.entrypoints: web,websecure
      traefik.http.routers.portainer-edge.service: portainer-edge
      traefik.http.routers.portainer-edge.rule: Host(`${PORTAINER_EDGE_HOST:-edge.${SITE:-localhost}}`)

      ## Homepage
      homepage.group: Docker
      homepage.name: Portainer
      homepage.icon: portainer.png
      homepage.href: https://${PORTAINER_HOST:-portainer.${SITE:-localhost}}
      homepage.description: Making Docker and Kubernetes management easy.

      homepage.widget.type: portainer
      homepage.widget.url: https://${PORTAINER_HOST:-portainer.${SITE:-localhost}}
      homepage.widget.env: ${HOMEPAGE_PORTAINER_ENV:-1}
      homepage.widget.key: ${HOMEPAGE_PORTAINER_KEY}
