version: '3'

services:
  nginx:
    image: nginx:${NGINX_IMAGE_VERSION:-stable-alpine}
    volumes:
      - './nginx/conf:/etc/nginx/conf.d'
      - './refs/server-private/page_default/:/srv/www/default'
      - './nginx/logs:/var/log/nginx/'
    networks:
      - 'srv'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.rule=Host(`${NGINX_HOST:-${SITE:-localhost}}`)'
      - 'traefik.http.services.nginx.loadbalancer.server.port=80'
