services:
  chyrp-lite:
    image: mrrbeu/chyrp-lite:${CHYRPLITE_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    hostname: chyrp-lite
    container_name: chyrp-lite

    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5

    networks:
      - server

    volumes:
      - './services/chyrp-lite/uploads:/var/www/html/uploads'
      - './services/chyrp-lite/db.sqlite:/db.sqlite'

    labels:
      ## Traefik
      traefik.enable: true
      traefik.http.routers.chyrp-lite.rule: Host(`${CHYRPLITE_HOST:-chyrp-lite.${SITE:-localhost}}`)
      traefik.http.services.chyrp-lite.loadbalancer.server.port: 80

      ## Homepage
      homepage.group: Web
      homepage.name: Chyrp lite
      homepage.icon: https://${CHYRPLITE_HOST:-chyrp-lite.${SITE:-localhost}}/favicon.svg
      homepage.href: https://${CHYRPLITE_HOST:-chyrp-lite.${SITE:-localhost}}
      homepage.description: An ultra-lightweight blogging engine, written in PHP.
