version: '3.8'

services:
  filestash:
    image: machines/filestash:${FILESTASH_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    hostname: filestash
    container_name: filestash

    environment:
      APPLICATION_URL: https://${FILESTASH_HOST:-filestash.${SITE:-localhost}}

    depends_on:
      - filestash-init

    networks:
      - server

    volumes:
      - './services/filestash/data:/app/data/state'

    labels:
      ## Traefik
      traefik.enable: true
      traefik.http.routers.filestash.rule: Host(`${FILESTASH_HOST:-filestash.${SITE:-localhost}}`)
      traefik.http.services.filestash.loadbalancer.server.port: 8334

      ## Homepage
      homepage.group: Web
      homepage.name: Filestash
      homepage.icon: filestash.png
      homepage.href: https://${FILESTASH_HOST:-filestash.${SITE:-localhost}}
      homepage.description: A modern web client for SFTP, S3, FTP, WebDAV, Git, Minio, LDAP, CalDAV, CardDAV, Mysql, Backblaze.

  filestash-init:
    image: machines/filestash:${FILESTASH_IMAGE_VERSION:-latest}
    platform: ${PLATFORM_ARCH:-linux/amd64}
    network_mode: none
    container_name: filestash-init

    environment:
      APPLICATION_URL: https://${FILESTASH_HOST:-filestash.${SITE:-localhost}}

    command: >
      if [ "$(ls -A /mnt_state/)" ]; then
        echo "/mnt_state/ is not empty. Ignoring!"
      else
        echo "/mnt_state/ is empty. Copying state files!"
        cp -n -r /app/data/state /mnt_state
      fi

    volumes:
      - './services/filestash/data:/mnt_state'

    labels:
      ## Traefik
      traefik.enable: false
