services:
  filegator:
    image: filegator/filegator:${FILEGATOR_IMAGE_VERSION:-latest-multiarch}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: filegator

    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:8080']
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5

    networks:
      - server

    volumes:
      - './services/filegator/private/:/var/www/filegator/private:z'
      - './storage/mount/gocryptfs:/var/www/filegator/repository:z'

    labels:
      ## Traefik
      traefik.enable: true

      traefik.http.services.filegator.loadbalancer.server.port: 8080

      traefik.http.routers.filegator.entrypoints: web,websecure
      traefik.http.routers.filegator.service: filegator
      traefik.http.routers.filegator.rule: Host(`${FILEGATOR_HOST:-filegator.${SITE:-localhost}}`)

      ## Homepage
      homepage.group: Files
      homepage.name: Filegator
      homepage.icon: filegator.png
      homepage.href: https://${FILEGATOR_HOST:-filegator.${SITE:-localhost}}
      homepage.description: Powerful Multi-User File Manager.
