version: '3'

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_IMAGE_VERSION:-latest}
    networks:
      - 'srv'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer/data:/data'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST:-portainer.${SITE:-localhost}}`)'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
      - 'traefik.http.routers.portainer.middlewares=basic_auth@docker'
