services:
  memos:
    image: neosmemo/memos:${MEMOS_IMAGE_VERSION:-latest}
    restart: unless-stopped
    platform: ${PLATFORM_ARCH:-linux/amd64}
    container_name: memos

    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:5230/site.webmanifest']
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 5

    networks:
      - server

    volumes:
      - './services/memos/data/:/var/opt/memos'

    labels:
      ## Traefik
      traefik.enable: true
      traefik.http.routers.memos.rule: Host(`${MEMOS_HOST:-memos.${SITE:-localhost}}`)
      traefik.http.services.memos.loadbalancer.server.port: 5230
      traefik.http.routers.memos.service: memos

      ## Homepage
      homepage.group: Web
      homepage.name: Memos
      homepage.icon: https://${MEMOS_HOST:-memos.${SITE:-localhost}}/android-chrome-192x192.png
      homepage.href: https://${MEMOS_HOST:-memos.${SITE:-localhost}}
      homepage.description: A privacy-first, lightweight note-taking service. Easily capture and share your great thoughts.
