version: '3'

services:
  gitredirect:
    image: morbz/docker-web-redirect
    restart: always
    container_name: git-redirect
    networks:
      - 'srv'
    environment:
      - 'traefik.enable=true'
      - 'traefik.http.routers.git-redirect.rule=Host(`${GITREDIRECT_HOST:-git.${SITE:-localhost}}`)'
      - 'traefik.http.services.git-redirect.loadbalancer.server.port=80'
      - 'VIRTUAL_HOST=${GITREDIRECT_HOST:-git.${SITE:-localhost}}'
      - 'REDIRECT_TARGET=${GITREDIRECT_DESTINATION:-${SITE:-localhost}}'
      - 'REDIRECT_TYPE=redirect'
