- datetime:
    text_size: xl
    locale: es
    format:
      dateStyle: long
      timeStyle: long

- resources:
    label: System
    cpu: true
    memory: true

- resources:
    label: Storage
    disk:
      - /
